app = 'icb-status-page'
primary_region = 'iad'

[build]
  image = "louislam/uptime-kuma:1.23.16-debian"

[[mounts]]
  source = 'kuma_data'
  destination = '/app/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
